import sqlite3
from datetime import datetime

conn = sqlite3.connect("crm.db")
cursor = conn.cursor()

# Insert Leads
for i in range(1, 21):
    cursor.execute("""
        INSERT INTO leads (name, email, company, source, status, score, sla, owner, description, created_at)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, (
        f"Lead {i}",
        f"lead{i}@example.com",
        f"Company {i}",
        "Ads" if i % 2 == 0 else "Social",
        "New" if i % 3 == 0 else "Contacted",
        "Hot",
        "24h",
        "Admin",
        "Generated by seed script",
        datetime.now()
    ))

# Insert Deals
for i in range(1, 11):
    cursor.execute("""
        INSERT INTO deals (title, value, pipeline, stage, created_at, closed_at)
        VALUES (?, ?, ?, ?, ?, ?)
    """, (
        f"Deal {i}",
        10000 * i,
        "Standard Pipeline",
        "Won" if i % 3 == 0 else "Lost",
        datetime.now(),
        datetime.now()
    ))

# Note: 'activities' table was referenced in the prompt but 'tasks' is used in the service based on existing schema.
# Skipping direct insert into 'activities' if it doesn't exist, relying on 'tasks' logic in service.
# If 'tasks' table exists, we can seed it.

conn.commit()
conn.close()

print("Sample data inserted successfully.")