from .auth_routes import auth_bp, social_bp
from .website_routes import website_bp
from .dashboard_routes import dashboard_bp
from .plan_routes import plan_bp
from .quick_action_routes import quick_actions_bp
from .chart_routes import chart_bp
from .contact_routes import contact_bp
from .lead_routes import lead_bp
from .deal_routes import deal_bp
from .note_file_routes import note_file_bp
from .organization_routes import organization_bp
from .analytics_routes import analytics_bp
from .task_routes import task_bp
from .calendar_routes import calendar_bp
from .activity_routes import activity_bp
from .automation_routes import automation_bp
from .inbox_routes import inbox_bp
from .webhook_routes import webhook_bp
from .channel_routes import channel_bp
from .message_routes import message_bp
from .conversation_routes import conversation_bp
from .call_routes import call_bp