from .auth_routes import auth_bp
from .website_routes import website_bp
from .dashboard_routes import dashboard_bp
from .plan_routes import plan_bp
from .quick_action_routes import quick_actions_bp
from .chart_routes import chart_bp
from .contact_routes import contact_bp
from .lead_routes import lead_bp
from .deal_routes import deal_bp
from .note_file_routes import note_file_bp