"""Add sales rules table

Revision ID: 0b7efb7cca65
Revises: aec6111b907b
Create Date: 2026-03-12 19:16:44.156692

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b7efb7cca65'
down_revision = 'aec6111b907b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_logs', schema=None) as batch_op:
        batch_op.alter_column('campaign_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'campaigns', ['campaign_id'], ['id'])

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.alter_column('campaign_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('leads_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'campaigns', ['campaign_id'], ['id'])

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.drop_index(batch_op.f('assigned_to'))
        batch_op.drop_index(batch_op.f('contact_id'))
        batch_op.drop_index(batch_op.f('ticket_number'))
        batch_op.create_unique_constraint(None, ['ticket_number'])
        batch_op.drop_constraint(batch_op.f('tickets_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('tickets_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['contact_id'], ['id'])
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['assigned_to'], ['id'])
        batch_op.drop_column('SLA Status')
        batch_op.drop_column('Last Updated')
        batch_op.drop_column('Priority')
        batch_op.drop_column('Ticket #')
        batch_op.drop_column('Category')
        batch_op.drop_column('Status')
        batch_op.drop_column('Ticket')
        batch_op.drop_column('Submitted By')
        batch_op.drop_column('Assignee')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_active')
        batch_op.drop_column('branch_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_active', mysql.DATETIME(), nullable=True))

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Assignee', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Submitted By', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Ticket', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('Status', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('Category', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('Ticket #', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('Priority', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('Last Updated', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('SLA Status', mysql.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('tickets_ibfk_2'), 'users', ['Assignee'], ['id'])
        batch_op.create_foreign_key(batch_op.f('tickets_ibfk_1'), 'contacts', ['Submitted By'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('ticket_number'), ['Ticket #'], unique=True)
        batch_op.create_index(batch_op.f('contact_id'), ['Submitted By'], unique=False)
        batch_op.create_index(batch_op.f('assigned_to'), ['Assignee'], unique=False)
        batch_op.drop_column('category')
        batch_op.drop_column('status')
        batch_op.drop_column('priority')

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('leads_ibfk_1'), 'campaigns', ['campaign_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('campaign_id',
               existing_type=sa.String(length=36),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('campaign_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('campaign_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###
