"""A descriptive message, e.g., 'Add status to Automation model'

Revision ID: 0cf92ae6d9bd
Revises: 
Create Date: 2026-02-12 23:50:03.388614

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '0cf92ae6d9bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('automation_rules')
# op.drop_table('whatsapp_accounts')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_email'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('due_date')

    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.alter_column('module',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('entity_type')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('details')
        batch_op.drop_column('entity_id')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)

    with op.batch_alter_table('automation_actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('template_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delay_minutes', sa.Integer(), nullable=True))
        batch_op.alter_column('automation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('action_type')
        batch_op.drop_column('action_value')

    with op.batch_alter_table('automation_conditions', schema=None) as batch_op:
        batch_op.alter_column('field',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('operator',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('value',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('automations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('trigger_event',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.drop_column('company_id')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('channel',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('config',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])
        batch_op.drop_column('type')

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'])

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.alter_column('lead_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_message')
        batch_op.drop_column('unread_count')
        batch_op.drop_column('last_message_at')
        batch_op.drop_column('state')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('pipeline',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('stage',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('owner',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'leads', ['lead_id'], ['id'])
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'])
        batch_op.drop_column('loss_reason')
        batch_op.drop_column('win_reason')
        batch_op.drop_column('closed_at')
        batch_op.drop_column('outcome')

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'users', ['assigned_user_id'], ['id'])
        batch_op.create_foreign_key(None, 'teams', ['assigned_team_id'], ['id'])
        batch_op.drop_column('updated_at')
        batch_op.drop_column('branch_id')
        batch_op.drop_column('owner')

    with op.batch_alter_table('login_history', schema=None) as batch_op:
        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=45),
               existing_nullable=True)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('channel', sa.String(length=50), nullable=True))
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('message_type')
        batch_op.drop_column('whatsapp_message_id')
        batch_op.drop_column('direction')

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])
        batch_op.drop_column('organization_name')

    with op.batch_alter_table('otp_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otp_verifications_email'), ['email'], unique=False)

    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_resets_reset_token'), ['reset_token'], unique=True)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('due_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'leads', ['lead_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])
        batch_op.create_foreign_key(None, 'deals', ['deal_id'], ['id'])
        batch_op.create_foreign_key(None, 'organizations', ['company_id'], ['id'])
        batch_op.drop_column('source_type')
        batch_op.drop_column('organization_id')
        batch_op.drop_column('source_id')
        batch_op.drop_column('task_time')
        batch_op.drop_column('task_date')

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('contact_id')
        batch_op.drop_column('subject')
        batch_op.drop_column('organization_id')
        batch_op.drop_column('priority')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('designation',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'teams', ['team_id'], ['id'])
        batch_op.drop_column('reset_token')
        batch_op.drop_column('branch_id')
        batch_op.drop_column('otp_expiry')
        batch_op.drop_column('otp')
        batch_op.drop_column('otp_code')
        batch_op.drop_column('last_active')
        batch_op.drop_column('reset_token_expiry')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token_expiry', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('last_active', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('otp_code', sa.VARCHAR(length=6), nullable=True))
        batch_op.add_column(sa.Column('otp', sa.VARCHAR(length=6), nullable=True))
        batch_op.add_column(sa.Column('otp_expiry', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('branch_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('reset_token', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('role',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('designation',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('department',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('organization_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('subject', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('contact_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'])
        batch_op.create_foreign_key(None, 'contacts', ['contact_id'], ['id'])
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('task_time', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('source_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('organization_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('source_type', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'])
        batch_op.alter_column('due_date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_resets_reset_token'))

    with op.batch_alter_table('otp_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otp_verifications_email'))

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direction', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_message_id', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('message_type', sa.VARCHAR(length=20), nullable=True))
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('channel')
        batch_op.drop_column('sender_id')
        batch_op.drop_column('sender_type')

    with op.batch_alter_table('login_history', schema=None) as batch_op:
        batch_op.alter_column('ip_address',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('branch_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('score',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('outcome', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('closed_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('win_reason', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('loss_reason', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('owner',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('stage',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('pipeline',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('state', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_message_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('unread_count', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('last_message', sa.TEXT(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['assigned_to'], ['id'])
        batch_op.create_foreign_key(None, 'leads', ['lead_id'], ['id'])
        batch_op.alter_column('lead_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('status')

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('config',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('channel',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('scheduled_at')

    with op.batch_alter_table('automations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('company_id', sa.INTEGER(), nullable=True))
        batch_op.alter_column('trigger_event',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('created_by')
        batch_op.drop_column('organization_id')
        batch_op.drop_column('branch_id')
        batch_op.drop_column('status')

    with op.batch_alter_table('automation_conditions', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('operator',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('field',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('automation_actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action_value', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('action_type', sa.VARCHAR(length=50), nullable=True))
        batch_op.alter_column('automation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('delay_minutes')
        batch_op.drop_column('template_id')
        batch_op.drop_column('type')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=False)

    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entity_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('details', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('entity_type', sa.VARCHAR(length=50), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.alter_column('company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('action',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('module',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DATETIME(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'])
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    op.create_table('password_reset_tokens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('otp', sa.VARCHAR(length=6), nullable=False),
    sa.Column('expiry', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_email'), ['email'], unique=False)

    op.create_table('whatsapp_accounts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('company_id', sa.INTEGER(), nullable=False),
    sa.Column('business_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('phone_number_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('access_token', sa.TEXT(), nullable=True),
    sa.Column('webhook_secret', sa.VARCHAR(length=255), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('automation_rules',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('entity_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('trigger_event', sa.VARCHAR(length=50), nullable=False),
    sa.Column('conditions_json', sqlite.JSON(), nullable=True),
    sa.Column('actions_json', sqlite.JSON(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('company_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
