"""empty message

Revision ID: 3e58a7764ec4
Revises: 3c6aa9f6b5ca
Create Date: 2026-03-09 15:19:18.757158

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3e58a7764ec4'
down_revision = '3c6aa9f6b5ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('record_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('date_time')
        batch_op.drop_column('user')
        batch_op.drop_column('record')

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('subject', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('contact_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assigned_to', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sla_due_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('closed_at', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('assigned_to'))
        batch_op.drop_index(batch_op.f('contact_id'))
        batch_op.drop_index(batch_op.f('ticket_number'))
        batch_op.create_unique_constraint(None, ['ticket_number'])
        batch_op.drop_constraint(batch_op.f('tickets_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('tickets_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['assigned_to'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['contact_id'], ['id'])
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'])
        batch_op.drop_column('Ticket #')
        batch_op.drop_column('Last Updated')
        batch_op.drop_column('Priority')
        batch_op.drop_column('Category')
        batch_op.drop_column('SLA Status')
        batch_op.drop_column('Ticket')
        batch_op.drop_column('Status')
        batch_op.drop_column('Assignee')
        batch_op.drop_column('Submitted By')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_active')
        batch_op.drop_column('branch_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_active', mysql.DATETIME(), nullable=True))

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Submitted By', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Assignee', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Status', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('Ticket', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('SLA Status', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('Category', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('Priority', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('Last Updated', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('Ticket #', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('tickets_ibfk_2'), 'users', ['Assignee'], ['id'])
        batch_op.create_foreign_key(batch_op.f('tickets_ibfk_1'), 'contacts', ['Submitted By'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('ticket_number'), ['Ticket #'], unique=True)
        batch_op.create_index(batch_op.f('contact_id'), ['Submitted By'], unique=False)
        batch_op.create_index(batch_op.f('assigned_to'), ['Assignee'], unique=False)
        batch_op.drop_column('closed_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('sla_due_at')
        batch_op.drop_column('category')
        batch_op.drop_column('status')
        batch_op.drop_column('priority')
        batch_op.drop_column('organization_id')
        batch_op.drop_column('assigned_to')
        batch_op.drop_column('contact_id')
        batch_op.drop_column('description')
        batch_op.drop_column('subject')
        batch_op.drop_column('ticket_number')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('record', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('user', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('date_time', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('created_at')
        batch_op.drop_column('record_name')
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
