"""add feedback table

Revision ID: a6b040e84b37
Revises: 
Create Date: 2026-03-07 16:25:05.569940

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a6b040e84b37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_resets_email'))
        batch_op.drop_index(batch_op.f('ix_password_resets_reset_token'))

    op.drop_table('password_resets')
    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['agent_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('branch_id')
        batch_op.drop_column('last_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_active', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('branch_id', mysql.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('agent_id')

    op.create_table('password_resets',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('otp', mysql.VARCHAR(length=6), nullable=False),
    sa.Column('reset_token', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False),
    sa.Column('verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_resets_reset_token'), ['reset_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_resets_email'), ['email'], unique=False)

    # ### end Alembic commands ###
